PREFIX lrppi: <http://landregistry.data.gov.uk/def/ppi/>
SELECT (COUNT(*) AS ?c)
WHERE {
  ?t a lrppi:TransactionRecord .
  ?t lrppi:transactionDate ?d .
  FILTER(?d >= "2024-01-01"^^<http://www.w3.org/2001/XMLSchema#date>)
}
LIMIT 1